# TCL File Generated by Component Editor 21.1
# Fri Apr 22 15:27:35 EDT 2022
# DO NOT MODIFY


# 
# Audio "Audio" v1.0
#  2022.04.22.15:27:35
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Audio
# 
set_module_property DESCRIPTION ""
set_module_property NAME Audio
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Audio
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file tonegen.sv SYSTEM_VERILOG PATH tonegen.sv

add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file tonegen.sv SYSTEM_VERILOG PATH tonegen.sv


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group vga
set_module_assignment embeddedsw.dts.name vga_ball
set_module_assignment embeddedsw.dts.vendor csee4840


# 
# display items
# 


# 
# connection point avalon_streaming_source_r
# 
add_interface avalon_streaming_source_r avalon_streaming start
set_interface_property avalon_streaming_source_r associatedClock clock
set_interface_property avalon_streaming_source_r associatedReset reset
set_interface_property avalon_streaming_source_r dataBitsPerSymbol 8
set_interface_property avalon_streaming_source_r errorDescriptor ""
set_interface_property avalon_streaming_source_r firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source_r maxChannel 0
set_interface_property avalon_streaming_source_r readyLatency 0
set_interface_property avalon_streaming_source_r ENABLED true
set_interface_property avalon_streaming_source_r EXPORT_OF ""
set_interface_property avalon_streaming_source_r PORT_NAME_MAP ""
set_interface_property avalon_streaming_source_r CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source_r SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source_r right_chan_ready ready Input 1
add_interface_port avalon_streaming_source_r sample_data_r data Output 16
add_interface_port avalon_streaming_source_r sample_valid_r valid Output 1


# 
# connection point avalon_streaming_source_l
# 
add_interface avalon_streaming_source_l avalon_streaming start
set_interface_property avalon_streaming_source_l associatedClock clock
set_interface_property avalon_streaming_source_l associatedReset reset
set_interface_property avalon_streaming_source_l dataBitsPerSymbol 8
set_interface_property avalon_streaming_source_l errorDescriptor ""
set_interface_property avalon_streaming_source_l firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source_l maxChannel 0
set_interface_property avalon_streaming_source_l readyLatency 0
set_interface_property avalon_streaming_source_l ENABLED true
set_interface_property avalon_streaming_source_l EXPORT_OF ""
set_interface_property avalon_streaming_source_l PORT_NAME_MAP ""
set_interface_property avalon_streaming_source_l CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source_l SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source_l left_chan_ready ready Input 1
add_interface_port avalon_streaming_source_l sample_data_l data Output 16
add_interface_port avalon_streaming_source_l sample_valid_l valid Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1

